# Generated by Django 2.2.14 on 2020-10-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('descrption', models.CharField(default='', max_length=2000)),
                ('image_1', models.ImageField(default='', upload_to='activity_images')),
                ('image_2', models.ImageField(default='', upload_to='activity_images')),
                ('video', models.FileField(default='', upload_to='videos')),
            ],
        ),
    ]
