# Generated by Django 2.2.14 on 2020-10-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image_1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='activity_images'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image_2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='activity_images'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='video',
            field=models.FileField(blank=True, default='', null=True, upload_to='videos'),
        ),
    ]
