# Generated by Django 2.2.14 on 2020-10-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201011_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='descrption',
            new_name='descrption_5',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='image_1',
            new_name='image_1_5',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='image_2',
            new_name='image_1_8',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='name',
            new_name='name_5',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='video',
            new_name='video_5',
        ),
        migrations.AddField(
            model_name='activity',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='descrption_8',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='activity',
            name='image_2_5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='activity_images'),
        ),
        migrations.AddField(
            model_name='activity',
            name='image_2_8',
            field=models.ImageField(blank=True, default='', null=True, upload_to='activity_images'),
        ),
        migrations.AddField(
            model_name='activity',
            name='name_8',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='video_8',
            field=models.FileField(blank=True, default='', null=True, upload_to='videos'),
        ),
    ]
