# Generated by Django 2.2.14 on 2020-10-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201011_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='descrption_5',
            new_name='description_5',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='descrption_8',
            new_name='description_8',
        ),
    ]
