# Generated by Django 2.2.14 on 2020-10-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201011_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='oneline_5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='activity',
            name='oneline_8',
            field=models.CharField(default='', max_length=500),
        ),
    ]
