# Generated by Django 2.2 on 2020-10-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201011_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='unique_one_word_name_5',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='unique_one_word_name_8',
            field=models.CharField(default='', max_length=10),
        ),
    ]
