# Generated by Django 2.2 on 2020-10-29 08:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201027_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description_5',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description_8',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
