# Generated by Django 2.2 on 2020-10-29 08:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201029_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description_5',
            field=ckeditor.fields.RichTextField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description_8',
            field=ckeditor.fields.RichTextField(default=1),
        ),
    ]
