# Generated by Django 2.2 on 2020-10-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201029_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='video_5',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
